### ISSUE TITLE
Request: include -3SD curves for WAZ?

### ISSUE THREAD

**Issue by lbramley** [RobertJohnston/SMART-Questionnaire#14]
Hi,

This may be somewhat outside the main scope of the tools here, but I was wondering if it'd be possible to also provide the calculate-field code for calculating the -3SD values for WAZ, so that this could be used in the SMART-Questionnaire form instead? Or is there a source I can use to find the appropriate equations to adapt it myself? In India for example, referrals are done for WAZ rather than WHZ, so we need the form to reflect that in its referral flagging. I had bodged together something using a lookup table, but it would be quite useful to have the actual calculations included in the form itself, like for the rest of the z-score calculations.

Thanks!
Laura

**Comment by RobertJohnston** [comment]
Hello Laura Bramley,

Thanks for reviewing the materials.  Currently only the <-6SD  and >+5SD
values for WAZ are calculated.  Then the measure is assessed against those
limits.  If outside of the limits, then the measure is flagged and a
request for remeasure is made.

Yes, it is possible to calculate the limit for <-3SD WAZ and integrate.  I
can share some materials with you.

I am very interested to know more about what you are doing and where.  I
know a little about the development of the integrated management of acute
protocol in India.  I know that it has been a long and difficult process to
get the program underway.

Thanks, Robert
